# Set min. snakemake version for compatability.
snakemake.utils.min_version("7.32.4")

# If the user doesn't pass --configfile or --config, look for config.yaml in the current working directory
if not config:
    configfile: "config.yaml"

include: "rules/common.smk"


rule all:
    input:
        # Run sci-rocket demultiplexing pipeline.
        expand(out("{experiment_name}/sci-dash/"), experiment_name=samples_unique["experiment_name"]),
       
        # Optional haplotyping rule (Mus musculus).
        expand(
            out("{experiment_name}/haplotyping/{sample_name}_{strain1}_{strain2}_haplotagged_readcounts.txt"),
            experiment_name=samples_unique_haplotyping["experiment_name"],
            sample_name=samples_unique_haplotyping["sample_name"],
            strain1=samples_unique_haplotyping["strain1"],
            strain2=samples_unique_haplotyping["strain2"],
        ),


# Load rules ----


include: "rules/step1_reads2fastq.smk"
include: "rules/step2_demultiplexing_fastq.smk"
include: "rules/step3_alignment.smk"
include: "rules/step4_dashboard.smk"
include: "rules/step5_haplotyping.smk"
