# Set min. snakemake version for compatability.
snakemake.utils.min_version("7.32.4")


# Skeleton config, parameters will be overwritten by user-defined config file.
configfile: f"{workflow.basedir}/examples/example_config.yaml"


# Import modules. ----

import sys

## Custom modules.
sys.path.append(f"{workflow.basedir}/rules/scripts/demultiplexing")
import preprocess

# Extract unique samples and perform sanity checks on sample sheet and barcodes
samples_unique = preprocess.get_samples(config)

# Extract optional haplotyping samples (Mus musculus)
samples_unique_haplotyping = preprocess.get_haplotyping_samples(samples_unique)

# Constrain wildcard values to resolve downstream mixtures. ----
wildcard_constraints:
    **preprocess.get_wildcard_constraints(samples_unique, ["sequencing_name", "experiment_name", "sample_name"]),
    **preprocess.get_wildcard_constraints(samples_unique_haplotyping, ["strain1", "strain2"]),


# Workflow output. ----

dir_output = config["dir_output"].rstrip("/")
def out(p: str) -> str:
    return f"{dir_output}/{p.lstrip('/')}"


# Scatter-gather settings.
scattergather:
    fastq_split=config["settings"]["scatter_fastq_split"],


rule all:
    input:
        # Run sci-rocket demultiplexing pipeline.
        expand(out("{experiment_name}/sci-dash/"), experiment_name=samples_unique["experiment_name"]),
       
        # Optional haplotyping rule (Mus musculus).
        expand(
            out("{experiment_name}/haplotyping/{sample_name}_{strain1}_{strain2}_haplotagged_readcounts.txt"),
            experiment_name=samples_unique_haplotyping["experiment_name"],
            sample_name=samples_unique_haplotyping["sample_name"],
            strain1=samples_unique_haplotyping["strain1"],
            strain2=samples_unique_haplotyping["strain2"],
        ),


# Load rules ----


include: "rules/step1_reads2fastq.smk"
include: "rules/step2_demultiplexing_fastq.smk"
include: "rules/step3_alignment.smk"
include: "rules/step4_dashboard.smk"
include: "rules/step5_haplotyping.smk"