import pytest
from pathlib import Path


@pytest.mark.parametrize("feature", ["Gene", "Velocyto"])
@pytest.mark.parametrize("output_type", ["raw", "filtered"])
def test_velocity_outputs_exist(feature: str, output_type: str):
    alignment_path = (
        Path(__file__).parent.parent
        / "output"
        / "velocity"
        / "alignment"
        / "ZAe-10hpf-28_Zebrafish_Solo.out"
    )
    assert alignment_path.is_dir()

    # barcodes_converted.tsv should be generated by the pipeline
    assert (alignment_path / feature / output_type / "barcodes_converted.tsv").exists()