#!/usr/bin/env python3
"""Generate config reference docs from the JSON schema without post-processing."""

from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path

import mkdocs_gen_files
import yaml
from json_schema_for_humans.generate import generate_from_filename
from json_schema_for_humans.generation_configuration import GenerationConfiguration
from json_schema_for_humans import jinja_filters


REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "workflow" / "schemas" / "config.schema.yaml"
DOC_PATH = Path("config_reference.md")
DOC_TEMPLATE_PATH = REPO_ROOT / "docs" / "config_reference.md"
AUTOGEN_TAG = "<!-- CONFIG_SCHEMA_REFERENCE -->"
TEMPLATE_OVERRIDES_DIR = REPO_ROOT / "docs" / "templates" / "md"


class _QuotedString(str):
    """Marker type for YAML dumping with explicit double quotes."""


class _QuotedStringDumper(yaml.SafeDumper):
    pass


def _represent_quoted_string(dumper: yaml.SafeDumper, data: _QuotedString):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style='"')


_QuotedStringDumper.add_representer(_QuotedString, _represent_quoted_string)


def _quote_string_values(value):
    if isinstance(value, dict):
        return {k: _quote_string_values(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_quote_string_values(v) for v in value]
    if isinstance(value, str):
        return _QuotedString(value)
    return value


def _yaml_example_with_quoted_strings(example_text: str) -> str:
    loaded = json.loads(example_text)
    dumped = yaml.dump(
        _quote_string_values(loaded),
        Dumper=_QuotedStringDumper,
        allow_unicode=True,
        sort_keys=False,
    )
    # PyYAML appends document end markers for some scalar values.
    return dumped.removesuffix("\n...\n").removesuffix("...\n")


# Override default filter to preserve YAML output while quoting string values.
jinja_filters.yaml_example = _yaml_example_with_quoted_strings


def _build_merged_template_base(tmpdir: Path) -> Path:
    """Merge upstream markdown templates with local overrides."""
    upstream_templates = Path(GenerationConfiguration(template_name="md").template_path).parent
    merged_templates = tmpdir / "templates" / "md"
    shutil.copytree(upstream_templates, merged_templates)

    if TEMPLATE_OVERRIDES_DIR.exists():
        for override_path in TEMPLATE_OVERRIDES_DIR.rglob("*"):
            if override_path.is_dir():
                continue
            relative_path = override_path.relative_to(TEMPLATE_OVERRIDES_DIR)
            target_path = merged_templates / relative_path
            target_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(override_path, target_path)

    return merged_templates / "base.md"


def render_markdown(schema_path: Path) -> str:
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        out_path = tmp_path / "config_reference.md"
        merged_template_base = _build_merged_template_base(tmp_path)
        generate_from_filename(
            str(schema_path),
            str(out_path),
            config=GenerationConfiguration(
                custom_template_path=str(merged_template_base),
                show_breadcrumbs=True,
                examples_as_yaml=True,
                template_md_options={"show_heading_numbers": False},
            ),
        )
        return out_path.read_text(encoding="utf-8")


def _strip_top_heading(markdown_content: str) -> str:
    lines = markdown_content.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    return "\n".join(lines).rstrip() + "\n"


def build_config_reference_page() -> str:
    template_text = DOC_TEMPLATE_PATH.read_text(encoding="utf-8")
    if AUTOGEN_TAG not in template_text:
        raise ValueError(f"Missing required tag in {DOC_TEMPLATE_PATH}: {AUTOGEN_TAG}")

    autogenerated_section = _strip_top_heading(render_markdown(SCHEMA_PATH))
    return template_text.replace(AUTOGEN_TAG, autogenerated_section)


def main() -> None:
    content = build_config_reference_page()
    with mkdocs_gen_files.open(DOC_PATH, "w") as handle:
        handle.write(content)
    mkdocs_gen_files.set_edit_path(DOC_PATH, str(DOC_TEMPLATE_PATH.relative_to(REPO_ROOT)))


main()
