name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pytest
      - name: Download test data
        run: wget -O - https://github.com/lauren-saunders-lab/sci-rocket-test-data/releases/download/2025.11.03/test-data.tgz | tar -xvzf - -C ci
      - name: test_fastq_from_aviti_one_run
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --verbose --configfile ci/test_fastq_from_aviti_one_run/config.yaml'
          stagein: ''
          show-disk-usage-on-error: true
      - run: pytest ci/test_fastq_from_aviti_one_run/tests -vvv
      - name: test_fastq_from_aviti_two_runs
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --verbose --configfile ci/test_fastq_from_aviti_two_runs/config.yaml'
          stagein: ''
          show-disk-usage-on-error: true
      - run: pytest ci/test_fastq_from_aviti_two_runs/tests -vvv

  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

