name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test_bcl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci-setup
      - name: Run BCL workflow integration tests
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: 'tests/integration/bcl'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --configfile tests/integration/bcl/config.yaml'
      - run: pytest tests/integration/bcl -vvv

  test_aviti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci-setup
      - name: Run AVITI workflow integration tests
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: 'tests/integration/aviti'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --configfile tests/integration/aviti/config.yaml'
      - run: pytest tests/integration/aviti -vvv

  test_velocity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/ci-setup
      - name: Run velocity workflow integration tests
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: 'tests/integration/velocity'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --configfile tests/integration/velocity/config.yaml'
      - run: pytest tests/integration/velocity -vvv

  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force