name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test_bcl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pytest pandas
      - name: Unit tests
        run: pytest tests/unit -vvv
      - name: Download test data
        run: mkdir -p tests/integration/data && wget -O - https://github.com/lauren-saunders-lab/sci-rocket-test-data/releases/download/2026.01.09/test-data.tgz | tar -xvzf - -C tests/integration/data
      - name: Run BCL workflow integration tests
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: 'tests/integration/bcl'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --verbose --configfile tests/integration/bcl/config.yaml'
      - run: pytest tests/integration/bcl -vvv

  test_aviti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pytest pandas
      - name: Unit tests
        run: pytest tests/unit -vvv
      - name: Download test data
        run: mkdir -p tests/integration/data && wget -O - https://github.com/lauren-saunders-lab/sci-rocket-test-data/releases/download/2026.01.09/test-data.tgz | tar -xvzf - -C tests/integration/data
      - name: Run AVITI workflow integration tests
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: 'tests/integration/aviti'
          snakefile: 'workflow/Snakefile'
          args: '--cores 4 --use-conda --conda-cleanup-pkgs cache -p --verbose --configfile tests/integration/aviti/config.yaml'
      - run: pytest tests/integration/aviti -vvv

  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

